USE ExamenVueling
GO
-- N CONVIERTE EL TEXTO EN NVARCHAR
-- U USER DEFINED TABLE
IF OBJECT_ID(N'ExamenVueling.dbo.Clients', N'U') IS NULL
BEGIN
-- Creamos la Tabla
CREATE TABLE dbo.Clients
(
	Id INT IDENTITY NOT NULL PRIMARY KEY,
	Nombre [NVARCHAR] (50) NOT NULL,
	Email [NVARCHAR] (250) NOT NULL,
	Role [NVARCHAR] (14) NOT NULL
);

END